# Generated by Django 5.2 on 2025-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='codigo',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
