# Generated by Django 5.2 on 2025-05-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_juego_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='detalle_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrito_items', to='core.detalleventa'),
        ),
    ]
