# Generated by Django 5.2 on 2025-05-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carritoitem_detalle_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='detalle_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_vinculados', to='core.detalleventa'),
        ),
    ]
