# Generated by Django 5.2 on 2025-05-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carritoitem_detalle_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='detalle_venta',
        ),
    ]
