# Generated by Django 5.2 on 2025-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_carritoitem_detalle_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
