# Generated by Django 5.2 on 2025-05-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carrito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.carrito'),
        ),
    ]
