# Generated by Django 5.2 on 2025-05-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_venta_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='juegos',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='core.juego'),
        ),
    ]
